In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics



In [2]:
df = pd.read_csv("https://data.heatonresearch.com/data/t81-558/iris.csv",
                na_values=['NA','?'])
display(df[0:5])

sepal_l  sepal_w  petal_l  petal_w      species
0      5.1      3.5      1.4      0.2  Iris-setosa
1      4.9      3.0      1.4      0.2  Iris-setosa
2      4.7      3.2      1.3      0.2  Iris-setosa
3      4.6      3.1      1.5      0.2  Iris-setosa
4      5.0      3.6      1.4      0.2  Iris-setosa

In [3]:
import pandas as pd
import io
import requests
import numpy as np
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_csv("https://data.heatonresearch.com/data/t81-558/iris.csv",
                na_values=['NA','?'])

#Convert to numpy - Classification
x = df[['sepal_l', 'sepal_w', 'petal_l', 'petal_w']].values
dummies = pd.get_dummies(df['species']) #Classification
species =  dummies.columns
y = dummies.values

#Build neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu')) #Hidden_layer 1
model.add(Dense(25, activation='relu')) #Hidden 2
model.add(Dense(y.shape[1],activation='softmax'))#Output

model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

W0729 14:27:02.568695 10032 deprecation.py:323] From F:\Amir\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\math_grad.py:1366: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0729 14:27:02.687469 10032 deprecation.py:323] From F:\Amir\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py:468: BaseResourceVariable.constraint (from tensorflow.python.ops.resource_variable_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Apply a constraint manually following the optimizer update step.


Train on 150 samples
Epoch 1/100
150/150 - 0s - loss: 1.2197
Epoch 2/100
150/150 - 0s - loss: 1.0788
Epoch 3/100
150/150 - 0s - loss: 0.9882
Epoch 4/100
150/150 - 0s - loss: 0.9282
Epoch 5/100
150/150 - 0s - loss: 0.8751
Epoch 6/100
150/150 - 0s - loss: 0.8255
Epoch 7/100
150/150 - 0s - loss: 0.7797
Epoch 8/100
150/150 - 0s - loss: 0.7352
Epoch 9/100
150/150 - 0s - loss: 0.6961
Epoch 10/100
150/150 - 0s - loss: 0.6545
Epoch 11/100
150/150 - 0s - loss: 0.6169
Epoch 12/100
150/150 - 0s - loss: 0.5840
Epoch 13/100
150/150 - 0s - loss: 0.5546
Epoch 14/100
150/150 - 0s - loss: 0.5267
Epoch 15/100
150/150 - 0s - loss: 0.5045
Epoch 16/100
150/150 - 0s - loss: 0.4832
Epoch 17/100
150/150 - 0s - loss: 0.4639
Epoch 18/100
150/150 - 0s - loss: 0.4460
Epoch 19/100
150/150 - 0s - loss: 0.4297
Epoch 20/100
150/150 - 0s - loss: 0.4139
Epoch 21/100
150/150 - 0s - loss: 0.3985
Epoch 22/100
150/150 - 0s - loss: 0.3854
Epoch 23/100
150/150 - 0s - loss: 0.3727
Epoch 24/100
150/150 - 0s - loss: 0.3609
Epoc

In [4]:
print(species)

Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')


In [5]:
pred = model.predict(x)
print("Shape: {pred.shape}")
print(pred)

Shape: {pred.shape}
[[9.97730196e-01 2.26980331e-03 8.24689261e-10]
 [9.94563758e-01 5.43623464e-03 7.93603938e-09]
 [9.96219337e-01 3.78066837e-03 4.11894607e-09]
 [9.92366254e-01 7.63369817e-03 1.71952461e-08]
 [9.97884452e-01 2.11555441e-03 7.26092853e-10]
 [9.96897459e-01 3.10252863e-03 8.69336270e-10]
 [9.95424569e-01 4.57538152e-03 5.90121596e-09]
 [9.96432900e-01 3.56703438e-03 2.24029240e-09]
 [9.90706742e-01 9.29322653e-03 3.69371413e-08]
 [9.94970798e-01 5.02919639e-03 5.47717027e-09]
 [9.98323739e-01 1.67620240e-03 2.93903873e-10]
 [9.94606793e-01 5.39320614e-03 5.54560531e-09]
 [9.95053768e-01 4.94620390e-03 6.55941346e-09]
 [9.95949745e-01 4.05029114e-03 7.24185245e-09]
 [9.99510884e-01 4.89115948e-04 1.46576137e-11]
 [9.99310493e-01 6.89500477e-04 2.85510157e-11]
 [9.98845816e-01 1.15411717e-03 1.58237506e-10]
 [9.97328877e-01 2.67117238e-03 1.26539046e-09]
 [9.97679889e-01 2.32009985e-03 3.82823689e-10]
 [9.97799218e-01 2.20078533e-03 6.51548815e-10]
 [9.95541871e-01 4.4

In [6]:
#Turn off scientific notation
np.set_printoptions(suppress=True)

In [7]:
print(y[0:10])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [8]:
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y,axis=1)
print(f"Predictions: {predict_classes}")
print(f"Expected: {expected_classes}")

Predictions: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Expected: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
print(species[predict_classes[1:10]])

Index(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'],
      dtype='object')


In [10]:
from sklearn.metrics import accuracy_score
correct = accuracy_score(expected_classes,predict_classes)
correct = accuracy_score(expected_classes,predict_classes)
print(f"Accuracy: {correct}")

Accuracy: 0.9733333333333334


In [11]:
#ad hoc prediction
sample_flower = np.array([[5.0,3.0,4.0,2.0]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred)
print(f"Predict that {sample_flower} is: {species[pred]}")

[[0.00034539 0.30592316 0.6937315 ]]
Predict that [[5. 3. 4. 2.]] is: Iris-virginica


In [12]:
#Predict two sample flowers
sample_flower = np.array([[5.0,3.0,4.0,2.0],[5.2,3.5,1.5,0.8]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred, axis=1)
print(f"Predict that these two flowers {sample_flower} are: {species[pred]}")

[[0.00034539 0.3059232  0.69373137]
 [0.9893811  0.0106189  0.00000002]]
Predict that these two flowers [[5.  3.  4.  2. ]
 [5.2 3.5 1.5 0.8]] are: Index(['Iris-virginica', 'Iris-setosa'], dtype='object')
